title: Rhino
description: Rhino is an open-source implementation of JavaScript written entirely in Java
google_analytics: 
show_downloads: true
remote_theme: pmarsceill/just-the-docs
aux_links:
  "Rhino on GitHub":
    - "//github.com/mozilla/rhino"
plugins:
  - jekyll-mentions
  - jekyll-redirect-from
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  tutorials:
    permalink: "/:collection/:path/"
    output: true
  tools:
    permalink: "/:collection/:path/"
    output: true
    
just_the_docs:
  collections:
    docs:
      name: Documentation
    tutorials:
      name: Tutorials
    tools:
      name: Tools