title: Rhino
description: Rhino is an open-source implementation of JavaScript written entirely in Java
google_analytics: 
show_downloads: true
remote_theme: pmarsceill/just-the-docs
logo: "/assets/images/rhino.png"
gems:
  - jekyll-mentions
